/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/renderer/components/AboutView.vue')['default']
    AppNavigation: typeof import('./src/renderer/components/AppNavigation.vue')['default']
    AppShell: typeof import('./src/renderer/layouts/AppShell.vue')['default']
    HomeView: typeof import('./src/renderer/components/HomeView.vue')['default']
    LocaleSwitcher: typeof import('./src/renderer/components/LocaleSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  }
}
